version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/app/data
      - ./config/https/nginx-https.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-network
  
  app:
    image: nginx:alpine
    container_name: openlayers
    expose:
      - 80
    volumes:
      - ./config/openlayers/data:/usr/share/nginx/openlayers
      - ./config/openlayers/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - proxy-network

  geoserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: geoserver-vectortiles
    container_name: geoserver
    expose:
      - 8080
    environment:
      - GEOSERVER_CSRF_DISABLED=true
    volumes:
      - proxy-geoserver-config:/opt/geoserver/data_dir
    networks:
      - proxy-network
      - ran-database-access-network

networks:
  proxy-network: {}
  ran-database-access-network:
    external: true

volumes:
  proxy-geoserver-config:
    external: true
